language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-node . #creataing a docker image
  - docker tag simple-node YOUR_DOCKER_HUB/simple-node:latest #build and tag image

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #login to dockerhub
  - docker push YOUR_DOCKER_HUB/simple-node #push image to docker